# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df68ac22ce24815140437a16d4a4aeb664dc370f40d3d62228315395db463ad8a31b9f7dacb9349818adbe56b69475245a1a13f390b1493e6a8c5a7458007305

test:
  secret_key_base: 20ed234fddd11550809637203948fd2b988c802a92e2906a2404825f53ba9e57a8174ad0cd5aa43680c209c0c8c4c1bbdd19eefa1c1585758a9ff3ada8b7ed6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
